image: node:8

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/

stages:
  # - test
  - build

tests:
  stage: test
  script:
    - npm set registry ${NPM_REGISTRY}
    - npm install
    - npm run test:cov
  tags:
    - docker
  allow_failure: false

compile:
  stage: build
  script:
    - npm set registry ${NPM_REGISTRY}
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - tags
  tags:
    - docker
